### ISSUE TITLE
Brando is not in your releases 

### ISSUE THREAD

**Issue by ipsq** [chrisdinn/brando#54]
https://github.com/chrisdinn/chrisdinn.github.com/tree/master/releases

**Comment by gatorcse** [comment]
I got it working using
```scala
resolvers += "brando" at "https://raw.githubusercontent.com/chrisdinn/chrisdinn.github.com/master/releases/"

libraryDependencies += "com.digital-achiever" %% "brando" % "3.0.1"
```
The raw githubusercontent is needed so that sbt downloads the files, instead of the github page listing the file. And the releases seem to be a version behind what the README says

**Comment by gramk** [comment]
Brando 3.0.2 has been published. I was able to use it by with the following sbt configuration (readme has been updated) : 

resolvers += "chrisdinn" at "http://chrisdinn.github.io/releases/"

libraryDependencies += "com.digital-achiever" %% "brando" % "3.0.2"
