### ISSUE TITLE
Repository Down

### ISSUE THREAD

**Issue by neilchaudhuri** [chrisdinn/brando#62]
As I write this, it looks like your [repository](http://chrisdinn.github.io/releases/) is down.

**Comment by damienlevin** [comment]
Sorry about the inconvenience. We released a snapshot version and haven't published the library yet : 
This should work :

resolvers += "chrisdinn" at "http://chrisdinn.github.io/releases/"
libraryDependencies += "com.digital-achiever" %% "brando" % "3.0.2"

**Comment by damienlevin** [comment]
We just published the last version, this should be resolved now.

resolvers += "chrisdinn" at "http://chrisdinn.github.io/releases/"
libraryDependencies += "com.digital-achiever" %% "brando" % "3.0.3"
